import AOSProvider from "@/components/aos/AOSProvider";
import ReduxProvider from "@/store/provider";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import type { Metadata } from "next";
import localFont from "next/font/local";
import ContactFloatButton from "@/components/ContactFloatButton";
import TawkTo from "@/components/TawkTo";

const poppins = localFont({
  src: "../public/font/Poppins/Poppins-Regular.ttf",
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "The Dopamine Cafe",
  description: "Generated by create next app",
  metadataBase: new URL("https://thedopaminecafe.com"),
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body style={{ overflow: "visible" }} className={poppins.className}>
        <ReduxProvider>
          <AOSProvider>
            {children}
            <ContactFloatButton />
            <TawkTo />
          </AOSProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
