import AOSProvider from "@/components/aos/AOSProvider";
import ReduxProvider from "@/store/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dopamine Coffee",
  description: "Generated by create next app",
  openGraph: {
    images: [{ url: "/dopamine_cafe.png" }],
  },
  twitter: {
    card: "summary_large_image",
    images: [{ url: "/dopamine_cafe.png" }],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AOSProvider>
            {children}
          </AOSProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
