import AOSProvider from "@/components/aos/AOSProvider";
import ReduxProvider from "@/store/provider";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Inter ki jagah Poppins import karein

// Poppins configuration
const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"], // 400 zaroori hai aapke liye
  variable: "--font-poppins" // CSS variable define karein
});

export const metadata: Metadata = {
  title: "The Dopamine Cafe",
  description: "Generated by create next app",
  metadataBase: new URL("https://thedopaminecafe.com"),
  openGraph: {
    images: [{ url: "/dopamine_cafe.png" }],
  },
  twitter: {
    card: "summary_large_image",
    images: [{ url: "/dopamine_cafe.png" }],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}> {/* Variable yahan add karein */}
      <body className={poppins.className}> {/* Body par default Poppins apply karein */}
        <ReduxProvider>
          <AOSProvider>
            {children}
          </AOSProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}